MODEL:
  TYPE: mlpnet
  NUM_CLASSES: 10
  LAYERS: 3
RESNET:
  TRANS_FUN: noisytalklinear_transform
RGRAPH:
  GROUP_NUM: 64
  DIM_FIRST: 512
  DIM_LIST: [512]
  FIXED_DINAMICITY: False
  LOSE_EDGE_PROBABILITY: [0.1, 0.9]
  SEED_TRAIN_END: 6
  SEED_TRAIN_START: 1
  SPARSITY: 0.128001
  TALK_MODE: dense
  UPPER: true
BN:
  USE_PRECISE_STATS: True
  NUM_SAMPLES_PRECISE: 1024
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: cifar10
  SPLIT: train
  BATCH_SIZE: 128
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 500
TEST:
  DATASET: cifar10
  SPLIT: test
  BATCH_SIZE: 200
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: False
OUT_DIR: .
